services:
  frontend:
    build:
      context: ./frontend
      args:
        VUE_APP_API_HOST: ${VUE_APP_API_HOST}
    restart: always
    ports: 
      - "${FRONTEND_PORT}:80"
    env_file:
      .env

  api:
    build:
      context: ./api
    restart: always
    ports: 
      - "${API_PORT}:80"
    volumes:
      - ${DIRECTORY}:${DIRECTORY}
    env_file:
      .env

