version: "3"

services:
  app:
    build:
      context: .
    command: "npm i && npm start"
    ports: 
      - 8080:8080
    volumes:
      - ./app:/var/app
      - ${DIRECTORY}:${DIRECTORY}
    env_file:
      .env
